# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2dd5be5634ec7a74eb9a1cd2c83a48ec677d8f203a4662b0f547eaaf705fd657d2fc9278e87a8167e072e3e3297d80e72bd58dd58e4b4412fdba41ba0871272

test:
  secret_key_base: 33e6afadbeb5b66d740f980a8076a44d237ad92d5ab06c341905d82867bc78ede9f278d4ab22d874fba08f2bbefa8a06f8037b120029e9873c47665d73e3feb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
